runtime: nodejs14  # Especifica a versão do Node.js

instance_class: F2  # Especifica a classe de instância

automatic_scaling:  # Configura o escalonamento automático
  target_cpu_utilization: 0.65

env_variables:  # Define variáveis de ambiente
  PORT: "8080"

entrypoint: npm run start  # Especifica o comando para iniciar sua aplicação

handlers:
- url: /static
  static_dir: build/static

- url: /.*
  static_files: build/index.html
  upload: build/index.html